#!/usr/bin/env perl

use strict;
use warnings;

use File::Find qw/find/;

my $(incdir, $extension) = @ARGV;

my @found;

sub wanted {
    push @found, $File::Find::name if /\.\Q${extension}\E$/;
}

find \&wanted, $incdir;

$, = " ";

print @found;
